### PR TITLE
fix: support Odoo 19.0's renamed _module_to_models__

### PR DESCRIPTION
**Pull request by XtremXpert**
## Summary

Odoo 19.0 renamed \`models.MetaModel.module_to_models\` to
\`_module_to_models__\` (name mangling via the trailing double
underscore that becomes \`_MetaModel__module_to_models\`).

Module-level access to \`module_to_models\` at line 34 then raises
\`AttributeError\` on \`import\`:

\`\`\`
AttributeError: type object 'MetaModel' has no attribute 'module_to_models'.
Did you mean: '_module_to_models__'?
\`\`\`

This breaks any module whose test suite imports \`FakeModelLoader\`
from this package on Odoo 19.0 — the import itself crashes before
any test runs.

Use \`getattr\` with a fallback to the new name. Same wheel keeps
working on 18.0 and on 19.0.

## Test plan

- [x] Module loads on Odoo 19.0 (registered \`FakeModelLoader\`
      import no longer raises)
- [x] Module still loads on Odoo 18.0 (the \`module_to_models\`
      attribute is still picked up by \`getattr\`)

### CODE REVIEW

**Comment by simahawk** [comment]
Thanks for your contrib. Please note that in v19 we can skip the use of this tool. 
I've just created this issue to serve as a reference https://github.com/OCA/odoo-test-helper/issues/52
